services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_pass
      POSTGRES_DB: expense_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URI: postgresql://expense_user:expense_pass@db:5432/expense_db
      DB_SSL: "false"
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data: